Output assets/images/modes.gif

Set TypingSpeed 75ms
Set FontSize 22
Set Width 1000
Set Height 300

# Image - default
Type "matugen color hsl 'hsl(114, 22%, 75%)' -m 'dark'"
Sleep 500ms
Enter

# Clear the screen
Sleep 2s
Ctrl+L

# Hex - triadic
Type "matugen color hex '#b3cdb0' -m 'light'"
Sleep 500ms
Enter

# Clear the screen
Sleep 2s
Ctrl+L

# Hsl - adjacent
Type "matugen color rgb 'rgb(179,205,176)' -m 'amoled'"
Sleep 500ms
Enter

Sleep 5s