# Where should we write the GIF?
Output assets/images/palette.gif

Set TypingSpeed 75ms
Set FontSize 22
Set Width 1000
Set Height 300

# Image - default
Type "matugen color hsl 'hsl(114, 22%, 75%)' -p 'default'"
Sleep 500ms
Enter

# Clear the screen
Sleep 2s
Ctrl+L

# Hex - triadic
Type "matugen color hex '#b3cdb0' -p 'triadic'"
Sleep 500ms
Enter

# Clear the screen
Sleep 2s
Ctrl+L

# Hsl - adjacent
Type "matugen color rgb 'rgb(179,205,176)' -p 'adjacent'"
Sleep 500ms
Enter

Sleep 5s