[package]
name = "matugen"
version = "0.8.2"
description = "A material you color generation tool with templates"
repository = "https://github.com/InioX/matugen-rs"
categories = ["command-line-utilities"]
exclude = [
    "default.nix",
    "flake.nix",
    "shell.nix",
    "example/*",
]
license = "GPL-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
material-color-utilities-rs = { version = "0.2.1", features = ["serde", "clap"] }
image = "0.24.6"
owo-colors = "3.5.0"
clap = { version = "4.2.4", features = ["derive"] }
color-eyre = { version = "0.6.2", default-features = false }
serde = { version = "1.0.160", features = ["derive"] }
toml = "0.7.3"
directories = "5.0"
resolve-path = "0.1.0"
regex = "1.8.1"
pretty_env_logger = "0.4.0"
log = "0.4.17"
paris-log = { version = "1.0.2", features = ["icons"] }
colors-transform = "0.2.11"
ariadne = "0.3.0"
chumsky = { version = "1.0.0-alpha.4", features = ["label"] }
criterion = "0.5.1"
logos = "0.13.0"

[[bench]]
name = "benchy"
harness = false

[patch.crates-io]
material-color-utilities-rs = { path = "./material-color-utilities-rs" }
